[Variables]
MainFontFace=Helvetica Neue
MainFontSizeText=11
SecondaryFontSizeText=15

;Folder Labels
FolderLabel0="SYSTEM"
FolderLabel0Path="C:\"

FolderLabel1="STORAGE"
FolderLabel1Path="D:\"

FolderLabel2="BACKUP"
FolderLabel2Path="E:\"

;Colors
AccentColor1=255,80,0,255
AccentColor2=200,200,200,255
AccentColor3=0,200,255,255
AccentColor4=255,255,255,255
AccentColor5=255,255,255,30
AccentColor6=255,255,255,70